export const BRIDGE_SOURCE = "yt-utils:youtube-player-bridge";

type PlayerTextRun = {
  text?: string;
};

export type TranslationLanguage = {
  languageCode?: string;
  languageName?: string;
};

export type CaptionTrack = {
  languageCode?: string;
  kind?: string;
  name?: {
    simpleText?: string;
    runs?: PlayerTextRun[];
  };
  displayName?: string;
  isTranslatable?: boolean;
  isTranslateable?: boolean;
  translationLanguage?: TranslationLanguage | null;
  vssId?: string;
};

export type AudioTrackMetadata = {
  id?: string;
  name?: string;
  isDefault?: boolean;
  isAutoDubbed?: boolean;
};

export type AudioTrack = {
  id?: string;
  C_?: AudioTrackMetadata;
  Iw?: AudioTrackMetadata;
  Z1?: AudioTrackMetadata;
  hs?: AudioTrackMetadata;
  US?: AudioTrackMetadata;
  yG?: AudioTrackMetadata;
  captionTracks?: CaptionTrack[];
};

const AUDIO_TRACK_METADATA_KEYS = ["C_", "Iw", "Z1", "US", "yG", "hs"] as const;

export type SubtitleSelection =
  | { mode: "off" }
  | { mode: "track"; track: CaptionTrack };

export type PlayerSnapshot = {
  videoId: string | null;
  audioTrack: AudioTrack | null;
  audioLanguage: string | null;
  captionTracks: CaptionTrack[];
  translationLanguages: TranslationLanguage[];
  currentCaptionTrack: CaptionTrack | null;
  subtitlesOn: boolean;
};

export type BridgeRequest = {
  source: typeof BRIDGE_SOURCE;
  kind: "request";
  id: string;
  action: "readSnapshot" | "applySelection";
  selection?: SubtitleSelection;
};

export type BridgeResponse = {
  source: typeof BRIDGE_SOURCE;
  kind: "response";
  id: string;
  result: PlayerSnapshot | boolean | null;
};

export function isSpanishLanguage(value: string | null | undefined): boolean {
  return normalizeLanguageCode(value)?.startsWith("es") ?? false;
}

export function isEnglishLanguage(value: string | null | undefined): boolean {
  return normalizeLanguageCode(value)?.startsWith("en") ?? false;
}

export function determineSubtitleSelection(
  snapshot: PlayerSnapshot,
): SubtitleSelection {
  if (isEnglishLanguage(snapshot.audioLanguage)) {
    const directEnglishTrack = snapshot.captionTracks.find((track) =>
      isEnglishLanguage(track.languageCode),
    );
    return directEnglishTrack
      ? { mode: "track", track: directEnglishTrack }
      : { mode: "off" };
  }

  if (normalizeLanguageCode(snapshot.audioLanguage)) {
    return { mode: "off" };
  }

  const autoGeneratedEnglishTrack = snapshot.captionTracks.find(
    (track) =>
      isEnglishLanguage(track.languageCode) &&
      isAutoGeneratedCaptionTrack(track),
  );
  return autoGeneratedEnglishTrack
    ? { mode: "track", track: autoGeneratedEnglishTrack }
    : { mode: "off" };
}

function isAutoGeneratedCaptionTrack(track: CaptionTrack): boolean {
  return (
    normalizeText(track.kind) === "asr" ||
    (normalizeText(track.vssId)?.startsWith("a.") ?? false)
  );
}

export function readSubtitleSignature(snapshot: PlayerSnapshot): string {
  const subtitlesPart = snapshot.subtitlesOn ? "on" : "off";
  const captionPart = getCaptionTrackSignature(snapshot.currentCaptionTrack);
  const audioPart = getAudioTrackSignature(snapshot.audioTrack);

  return [subtitlesPart, captionPart, audioPart].join("|");
}

export function matchesSubtitleSelection(
  snapshot: PlayerSnapshot,
  selection: SubtitleSelection,
): boolean {
  if (selection.mode === "off") {
    return snapshot.subtitlesOn === false;
  }

  return (
    snapshot.subtitlesOn === true &&
    getCaptionTrackSignature(snapshot.currentCaptionTrack) ===
      getCaptionTrackSignature(selection.track)
  );
}

function normalizeLanguageCode(
  value: string | null | undefined,
): string | null {
  if (!value) {
    return null;
  }

  const normalized = value
    .trim()
    .toLowerCase()
    .split(".")[0]
    .replaceAll("_", "-");
  return normalized.length > 0 ? normalized : null;
}

function getCaptionTrackSignature(track: CaptionTrack | null): string {
  if (!track) {
    return "caption:none";
  }

  return [
    "caption",
    signaturePart(normalizeLanguageCode(track.languageCode)),
    signaturePart(track.kind),
    signaturePart(track.vssId),
    signaturePart(
      normalizeLanguageCode(track.translationLanguage?.languageCode),
    ),
  ].join(":");
}

function getAudioTrackSignature(track: AudioTrack | null): string {
  if (!track) {
    return "audio:none";
  }

  const metadata = readAudioTrackMetadata(track);
  return [
    "audio",
    signaturePart(normalizeLanguageCode(metadata?.id || track.id)),
    signaturePart(normalizeText(metadata?.name)),
    metadata?.isAutoDubbed ? "auto" : "original",
  ].join(":");
}

/**
 * YouTube renames this nested object without notice. Precedence is C_, Iw, Z1,
 * US, yG, then hs. Each field falls through independently. The top-level id is
 * the final id fallback because it can be an opaque identifier.
 */
export function readAudioTrackMetadata(
  track: AudioTrack | null,
): AudioTrackMetadata | null {
  if (!track) {
    return null;
  }

  const aliases = AUDIO_TRACK_METADATA_KEYS.map((key) => track[key]);
  const metadata: AudioTrackMetadata = {
    id: readFirstValue([...aliases.map(({ id } = {}) => id), track.id]),
    name: readFirstValue(aliases.map(({ name } = {}) => name)),
    isDefault: readFirstValue(aliases.map(({ isDefault } = {}) => isDefault)),
    isAutoDubbed: readFirstValue(
      aliases.map(({ isAutoDubbed } = {}) => isAutoDubbed),
    ),
  };

  return Object.values(metadata).some((value) => value != null)
    ? metadata
    : null;
}

function signaturePart(value: string | null | undefined): string {
  return value || "none";
}

function normalizeText(value: string | null | undefined): string | null {
  if (!value) {
    return null;
  }

  const normalized = value.trim().toLowerCase();
  return normalized.length > 0 ? normalized : null;
}

function readFirstValue<T>(values: Array<T | null | undefined>): T | undefined {
  return values.find((value): value is T => value != null);
}
