import watchPanelAutoOpenFeature from "./features/watch-panel-auto-open/content";
import audioLanguageSubtitlePolicyFeature from "./features/audio-language-subtitle-policy/content";
import autoSwitchToVideosTabFeature from "./features/auto-switch-to-videos-tab/content";
import engagementPanelScrollContainmentFeature from "./features/engagement-panel-scroll-containment/content";
import markAsSeenFeature from "./features/mark-as-seen/content";
import playbackSpeedFeature from "./features/playback-speed/content";
import subscriptionsGridDensityFeature from "./features/subscriptions-grid-density/content";
import seenCardDimmingFeature from "./features/seen-card-dimming/content";
import subscriptionsFeedControlsFeature from "./features/subscriptions-feed-controls/content";
import subscriptionsShortsRemovalFeature from "./features/subscriptions-shorts-removal/content";
import { FeatureRegistry } from "./shared/feature-registry";

const registry = new FeatureRegistry();
registry.register(markAsSeenFeature);
registry.register(audioLanguageSubtitlePolicyFeature);
registry.register(playbackSpeedFeature);
registry.register(engagementPanelScrollContainmentFeature);
registry.register(watchPanelAutoOpenFeature);
registry.register(subscriptionsFeedControlsFeature);
registry.register(seenCardDimmingFeature);
registry.register(subscriptionsShortsRemovalFeature);
registry.register(subscriptionsGridDensityFeature);
registry.register(autoSwitchToVideosTabFeature);
