#!/usr/bin/env sh
staged_files=$(git diff --cached --name-only --diff-filter=ACM)

if [ -n "$staged_files" ]; then
	printf '%s\n' "$staged_files" | xargs npx biome check --write
	printf '%s\n' "$staged_files" | xargs git add
fi

npm run check
